# $Id: Makefile.win,v 1.1 2006/12/04 16:01:12 mascarenhas Exp $

T= rings
V= 1.1.0
CONFIG= ./config.win

include $(CONFIG)

SRCS= src/rings.c
OBJS= src/rings.obj

src/$(LIBNAME) : $(OBJS)
	link /dll /out:src/$(LIBNAME) $(OBJS) $(LUA_LIB)

install:
	mkdir -p $(LUA_LIBDIR)
	copy src/$(LIBNAME) $(LUA_LIBDIR)
	mkdir -p $(LUA_DIR)
	copy src/stable.lua $(LUA_DIR)

clean:
	del src/$(LIBNAME) $(OBJS)
