# $Id: Makefile.win,v 1.2 2006/12/04 18:32:44 mascarenhas Exp $

T= rings
V= 1.1.0

include config.win

SRCS= src\rings.c
OBJS= src\rings.obj

.c.obj:
	$(CC) /c /Fo$@ $(CFLAGS) $<

src\$(LIBNAME) : $(OBJS)
	link /dll /def:src\$T.def /out:src\$(LIBNAME) $(OBJS) $(LUA_LIB)

install:
	IF NOT EXIST $(LUA_LIBDIR) mkdir $(LUA_LIBDIR)
	copy src\$(LIBNAME) $(LUA_LIBDIR)
	IF NOT EXIST $(LUA_DIR) mkdir $(LUA_DIR)
	copy src\stable.lua $(LUA_DIR)

clean:
	del src\$(LIBNAME) $(OBJS)
